stages:
  data_ingestion:
    cmd: python3 src/cnnClassifier/pipeline/data_ingestion_stage_01.py
    deps:
      - src/cnnClassifier/pipeline/data_ingestion_stage_01.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:
    cmd: python3 src/cnnClassifier/pipeline/prepare_base_model_stage_02.py
    deps:
      - src/cnnClassifier/pipeline/prepare_base_model_stage_02.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python3 src/cnnClassifier/pipeline/training_stage_03.py
    deps:
      - src/cnnClassifier/pipeline/training_stage_03.py
      - src/cnnClassifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python3 src/cnnClassifier/pipeline/evaluation_stage_04.py
    deps:
      - src/cnnClassifier/pipeline/evaluation_stage_04.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
